version: "3.8"
services:
    db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: root_password
            MYSQL_DATABASE: db
            MYSQL_USER: user
            MYSQL_PASSWORD: user_password
        ports:
            - "3306:3306"
        expose:
            - "3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
        driver: local